### ISSUE TITLE
Error getting households

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-AndroidClient#3]
Getting a not null error when loading the household from the Server. Seems to be an error placing the value in the DB. Error on line 137 of HouseholdDataSource

04-26 13:33:53.581  20563-20619/com.example.android.virtualpantry E/SQLiteLog﹕ (1299) abort at 11 in [INSERT OR REPLACE  INTO Households(ID,Description,Name) VALUES (?,?,?)]: NOT NULL constraint failed: Households.Version
04-26 13:33:53.598  20563-20619/com.example.android.virtualpantry E/SQLiteDatabase﹕ Error inserting ID=10 Description=my first household Name=house1
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Households.Version (code 1299)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:790)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:926)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1581)
            at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1497)
            at com.example.android.virtualpantry.Database.HouseholdDataSource$2.doInBackground(HouseholdDataSource.java:145)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:35)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

04-26 13:34:59.618  20563-20620/com.example.android.virtualpantry E/SQLiteLog﹕ (1299) abort at 11 in [INSERT OR REPLACE  INTO Households(ID,Description,Name) VALUES (?,?,?)]: NOT NULL constraint failed: Households.Version
04-26 13:34:59.619  20563-20620/com.example.android.virtualpantry E/SQLiteDatabase﹕ Error inserting ID=10 Description=my first household Name=house1
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Households.Version (code 1299)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:790)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:926)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1581)
            at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1497)
            at com.example.android.virtualpantry.Database.HouseholdDataSource$2.doInBackground(HouseholdDataSource.java:145)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:35)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by bradwarrum** [comment]
This is fixed and will be pushed with the next commit

**Comment by bradwarrum** [comment]
If you're still having issues with this it may be because the database is not properly upgrading to the new schema.  Let me know if this happens

**Comment by bradwarrum** [comment]
Pull commit https://github.com/bradwarrum/CS307-AndroidClient/commit/74e64fa353049d99d71d8a2e49dbeffdb6c30da9 if you are still having problems and check the database version in the logcat output
