### ISSUE TITLE
New Error on get household

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-AndroidClient#5]
04-28 12:19:03.548    2954-2954/com.example.android.virtualpantry E/onCreate﹕ householdID=3
04-28 12:19:03.689    2954-2973/com.example.android.virtualpantry E/SQLiteLog﹕ (1) near ",": syntax error
04-28 12:19:03.690    2954-2973/com.example.android.virtualpantry E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #2
    Process: com.example.android.virtualpantry, PID: 2954
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteException: near ",": syntax error (code 1): , while compiling: SELECT (Name, Description) FROM Households WHERE ID=?;
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
            at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
            at com.example.android.virtualpantry.Database.HouseholdDataSource$3.fetchLocalInfo(HouseholdDataSource.java:259)
            at com.example.android.virtualpantry.Database.HouseholdDataSource$3.doInBackground(HouseholdDataSource.java:253)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:35)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by gsczechowski** [comment]
Removed parentheses from queries. Fixed it.
