### ISSUE TITLE
Database crash

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-AndroidClient#6]
04-29 00:30:15.101    2693-2715/com.example.android.virtualpantry E/SQLiteLog﹕ (1299) abort at 9 in [INSERT INTO ShoppingLists(Orphaned,ListID,Name) VALUES (?,?,?)]: NOT NULL constraint failed: ShoppingLists.HouseholdID
04-29 00:30:15.120    2693-2715/com.example.android.virtualpantry E/SQLiteDatabase﹕ Error inserting Orphaned=0 ListID=3 Name=list1
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: ShoppingLists.HouseholdID (code 1299)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.example.android.virtualpantry.Database.HouseholdDataSource$3.doInBackground(HouseholdDataSource.java:236)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:35)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by gsczechowski** [comment]
04-29 00:46:11.455    2801-2820/com.example.android.virtualpantry E/SQLiteLog﹕ (1) no such table: ShoppingListItem
04-29 00:46:12.305    2801-2820/com.example.android.virtualpantry E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: com.example.android.virtualpantry, PID: 2801
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteException: no such table: ShoppingListItem (code 1): , while compiling: UPDATE ShoppingListItem SET Orphaned=? WHERE ListID = ?
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1574)
            at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
            at com.example.android.virtualpantry.Database.PersistenceTask.updateLocalList(PersistenceTask.java:112)
            at com.example.android.virtualpantry.Database.ListDataSource$5.doInBackground(ListDataSource.java:325)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:35)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by gsczechowski** [comment]
04-29 01:06:06.842  16281-16324/com.example.android.virtualpantry E/SQLiteLog﹕ (1) no such column: S.Quantity
    --------- beginning of crash
04-29 01:06:06.844  16281-16324/com.example.android.virtualpantry E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #3
    Process: com.example.android.virtualpantry, PID: 16281
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteException: no such column: S.Quantity (code 1): , while compiling: SELECT I.PackageQuantity, I.PackageUnits, I.PackageName, I.Description, S.UPC, S.Quantity, S.Fractional, S.CartQuantity, S.CartFractional FROM ShoppingListItems S INNER JOIN InventoryItems I ON (S.UPC=I.UPC AND S.HouseholdID=S.UPC) WHERE S.ListID=?;
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:897)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:508)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1426)
            at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1365)
            at com.example.android.virtualpantry.Database.ListDataSource$5.doInBackground(ListDataSource.java:330)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:35)
            at com.example.android.virtualpantry.Database.PersistenceTask.doInBackground(PersistenceTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by gsczechowski** [comment]
All working currently
